apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: home
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: home
    spec:
      containers:
      - image: samiksha18/hera1-21:latest
        name: homec
        env:
        - name: DB_URL
          value: "mongodb://Amartya:p2GQJ4dSGw4AI3Lf@cluster0-shard-00-00.ppvul.mongodb.net"
        ports:
        - containerPort: 3003
        resources: {}
status: {}


