apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login
    spec:
      containers:
      - image: samiksha18/hera3-21:latest
        name: loginc
        env:
        - name: DB_URL
          value: "mongodb+srv://Amartya:p2GQJ4dSGw4AI3Lf@cluster0.ppvul.mongodb.net"
        ports:
        - containerPort: 3001
        resources: {}
status: {}


